sonar.projectKey=kio7po_comic-tracker-frontend
sonar.organization=kio7po
# Path is relative to the sonar-project.properties file.
sonar.sources=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=comic-tracker
#sonar.projectVersion=1.0
