spring:
  sql:
    init:
      mode: always
  datasource:
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  application:
    name: comic-tracker
  jpa:
    hibernate:
      ddl-auto: validate
  threads:
    virtual:
      enabled: 'true'
  mvc:
    problemdetails:
      enabled: true

jwt:
  sign-key: ${JWT_SIGN_KEY}
  issuer: comic-tracker
  audience: comic-tracker
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 30
  refresh-token-secure: true
